// @ts-nocheck
import * as __fd_glob_50 from "../content/docs/openprinter-cloud/sdk.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/openprinter-cloud/list-jobs.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/openprinter-cloud/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/openprinter-cloud/errors.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/openprinter-cloud/create-job.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/openprinter-cloud/authentication.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/agent-gateway/serverSendsPrintJob.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/agent-gateway/serverSendsHello.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/agent-gateway/serverSendsHeartbeat.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/agent-gateway/serverSendsAuthRejected.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/agent-gateway/serverSendsAuthChallenge.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/agent-gateway/serverSendsAuthAccepted.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/agent-gateway/serverRequestsPrinterInventory.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/agent-gateway/serverInvalidatesConfiguration.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/agent-gateway/serverDisconnects.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/agent-gateway/serverCancelsJob.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/agent-gateway/index.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/agent-gateway/agentSendsPrinterInventoryChanged.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/agent-gateway/agentSendsPrinterInventory.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/agent-gateway/agentSendsHello.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/agent-gateway/agentSendsHeartbeat.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/agent-gateway/agentSendsDiagnostics.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/agent-gateway/agentSendsAuthResponse.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/agent-gateway/agentReportsSubmission.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/agent-gateway/agentReportsFailure.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/agent-gateway/agentAcknowledgesJob.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/why-oppa-exists.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/virtual-printer.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/server-sdk.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/security.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/release-process.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/protocol.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/product-configuration.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/printer-discovery.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/print-documents.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/nodejs-integration.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/job-delivery.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/idempotency.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/getting-started.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/example-server.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/diagnostics.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/deep-link-pairing.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/contributing.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/build-oppa.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/authentication-flow.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/architecture.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/agent-lifecycle.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/openprinter-cloud/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/agent-gateway/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "agent-gateway/meta.json": __fd_glob_1, "openprinter-cloud/meta.json": __fd_glob_2, }, {"agent-lifecycle.mdx": __fd_glob_3, "architecture.mdx": __fd_glob_4, "authentication-flow.mdx": __fd_glob_5, "build-oppa.mdx": __fd_glob_6, "contributing.mdx": __fd_glob_7, "deep-link-pairing.mdx": __fd_glob_8, "diagnostics.mdx": __fd_glob_9, "example-server.mdx": __fd_glob_10, "getting-started.mdx": __fd_glob_11, "idempotency.mdx": __fd_glob_12, "index.mdx": __fd_glob_13, "job-delivery.mdx": __fd_glob_14, "nodejs-integration.mdx": __fd_glob_15, "print-documents.mdx": __fd_glob_16, "printer-discovery.mdx": __fd_glob_17, "product-configuration.mdx": __fd_glob_18, "protocol.mdx": __fd_glob_19, "release-process.mdx": __fd_glob_20, "security.mdx": __fd_glob_21, "server-sdk.mdx": __fd_glob_22, "virtual-printer.mdx": __fd_glob_23, "why-oppa-exists.mdx": __fd_glob_24, "agent-gateway/agentAcknowledgesJob.mdx": __fd_glob_25, "agent-gateway/agentReportsFailure.mdx": __fd_glob_26, "agent-gateway/agentReportsSubmission.mdx": __fd_glob_27, "agent-gateway/agentSendsAuthResponse.mdx": __fd_glob_28, "agent-gateway/agentSendsDiagnostics.mdx": __fd_glob_29, "agent-gateway/agentSendsHeartbeat.mdx": __fd_glob_30, "agent-gateway/agentSendsHello.mdx": __fd_glob_31, "agent-gateway/agentSendsPrinterInventory.mdx": __fd_glob_32, "agent-gateway/agentSendsPrinterInventoryChanged.mdx": __fd_glob_33, "agent-gateway/index.mdx": __fd_glob_34, "agent-gateway/serverCancelsJob.mdx": __fd_glob_35, "agent-gateway/serverDisconnects.mdx": __fd_glob_36, "agent-gateway/serverInvalidatesConfiguration.mdx": __fd_glob_37, "agent-gateway/serverRequestsPrinterInventory.mdx": __fd_glob_38, "agent-gateway/serverSendsAuthAccepted.mdx": __fd_glob_39, "agent-gateway/serverSendsAuthChallenge.mdx": __fd_glob_40, "agent-gateway/serverSendsAuthRejected.mdx": __fd_glob_41, "agent-gateway/serverSendsHeartbeat.mdx": __fd_glob_42, "agent-gateway/serverSendsHello.mdx": __fd_glob_43, "agent-gateway/serverSendsPrintJob.mdx": __fd_glob_44, "openprinter-cloud/authentication.mdx": __fd_glob_45, "openprinter-cloud/create-job.mdx": __fd_glob_46, "openprinter-cloud/errors.mdx": __fd_glob_47, "openprinter-cloud/index.mdx": __fd_glob_48, "openprinter-cloud/list-jobs.mdx": __fd_glob_49, "openprinter-cloud/sdk.mdx": __fd_glob_50, });